### PR TITLE
Implement a text-only mode.

### PR DESCRIPTION
**Pull request by Xyaneon**
This also uses `argparse` for command line argument parsing and adds some other small fixes. @jacob1 , could you please review this and merge if it looks good?

### CODE REVIEW

**Comment by Xyaneon** [comment]
Merging this would fix #10  .

**Comment by jacob1** [comment]
Looks good to me (assuming it works). Don't see any obvious mistakes besides the obvious mistakes that it fixes :P

**Comment by KhalilKhalaf** [comment]
Alright is there anything I can do .. :p

**Comment by Xyaneon** [comment]
@KKLTU Still [plenty to do](https://github.com/WarriorIng64/LTUAssistant/issues), and this doesn't even touch some of the other functionality we were supposed to have implemented. Feel free to start a branch. I'll be up tonight working some more on the calendar support and some other things.

**Pull request merged**
